CREATE TABLE users(
	id TEXT PRIMARY KEY UNIQUE NOT NULL,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	password VARCHAR(100) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	role TEXT NOT NULL
);